baseURL = "http://janvt.dev"
title = "janvt"

theme = "hugo-coder"

languageCode = "en-us"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "janvt"

[params]
    author = "Jan vT"
    info = "software engineer & feedback cycle nerd"
    description = "janvt - developer portfolio"
    keywords = "developer,coder,freelancer"
    avatarurl = "images/janvt.jpg"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/janvt/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/janvanthoor/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/janvt/"

[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 1
    url  = "/contact/"