[build]
publish = "public"
command = "hugo --gc --minify -b /"

[context.production.environment]
HUGO_VERSION = "0.61.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b /"

[context.deploy-preview.environment]
HUGO_VERSION = "0.61.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
